# Generated by Django 5.2.6 on 2025-09-07 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='chatbot_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='support_goals',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='website_url',
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.URLField(blank=True)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('business_type', models.CharField(blank=True, max_length=50)),
                ('chatbot_name', models.CharField(blank=True, max_length=100)),
                ('tone', models.CharField(blank=True, max_length=50)),
                ('support_goals', models.TextField(blank=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='user.bot')),
            ],
        ),
    ]
