# Generated by Django 5.2.6 on 2025-09-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_conversation_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='satisfied',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
