# Generated by Django 5.2.6 on 2025-09-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_message_satisfied'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
