# Generated by Django 5.2.6 on 2025-09-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_conversation_is_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='is_resolved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
