# Generated by Django 5.2.6 on 2025-09-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_conversation_is_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bot',
            name='embed_code',
            field=models.TextField(blank=True),
        ),
    ]
